apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-vars
  labels:
    app: front
data:
  test1: mytest1
  test2: mytest2
  script: |
    echo $TESTA and $TESTB > /tmp/testfile.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-env
  labels: 
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata: 
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: TESTA
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: test1
            - name: TESTB
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: test1
          volumeMounts:
          - name: script-volume
            mountPath: /opt
      volumes:
        - name: script-volume
          configMap:
            name: vars
            items:
            - key: script
              path: script.sh