apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: admin
  password: "123454678"
  username1: admin1
  password1: "87654321"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env:
      - name: USERTEST
        valueFrom:
          secretKeyRef:
            name: secret1
            key: username1
      - name: PASSWORDTEST
        valueFrom:
          secretKeyRef:
            name: secret1
            key: password1
    volumeMounts:
    - name: test
      mountPath: /opt
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: secret1
